name: Meta Dumpling
title: The marvels of Dumplings
description: The marvels of Dumplings
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Giriş Sayfası
    url: /
  - title: Hakkında
    url: /about
  - title: Bizim Hikayemiz
    url: /our_story
  - title: Bize Ulaşın
    url: /contact
  # - title: Feed
  #   url: /feed.xml
email: meta.dumpling@gmail.com
# See: https://disqus.com/
disqus_username: metadumpling
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xwkjpeno
