name: Meta Dumpling
title: The marvels of Dumplings
description: The marvels of Dumplings
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: Product List
    url: /all-about-meta-dumpling
  - title: Tags
    url: /tags
  - title: About
    url: /about
  - title: Email Us
    url: /contact
  # - title: Feed
  #   url: /feed.xml
email: meta.dumpling@gmail.com
# See: https://disqus.com/
disqus_username: metadumpling
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xwkjpeno
banner_name: All About Meta Dumpling
